steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
            '--build-arg', 'REACT_APP_API_URL=https://maduvan-bank-app-backend-1096816685031.northamerica-northeast2.run.app/api/v1',
            '-t', 'northamerica-northeast2-docker.pkg.dev/gcp-class-17/maduvan-app-repo/bank-app-frontend', 
            '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
            'northamerica-northeast2-docker.pkg.dev/gcp-class-17/maduvan-app-repo/bank-app-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 
            'deploy', 
            'maduvan-bank-app-frontend',
            '--image=northamerica-northeast2-docker.pkg.dev/gcp-class-17/maduvan-app-repo/bank-app-frontend:latest',
            '--region=northamerica-northeast2',
            '--no-invoker-iam-check',
            '--port=80']

options:
  logging: CLOUD_LOGGING_ONLY